# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWi1bbhEfYyc6FN_dtgPUXhIyOsyBtM8
"""

dados_funcionario = {'nome':'joao','idade':32,'altura':1.65,'ativo':True,'dependentes':{'filhos':2,'conjuge':True}}

dados_funcionario ['salario']=1500.00

dados_funcionario ['dependentes'] ['filhos']*100+ dados_funcionario ['dependentes'] ['conjuge']

dados_funcionario ['dependentes'] ['filhos']*100.00+ dados_funcionario ['dependentes'] ['conjuge']*100+ dados_funcionario ['salario']

dados_funcionario.pop('altura')

dados_funcionario.keys()

dados_funcionario.values()

dados_funcionario.items()

dados_salvo = dados_funcionario.copy()
print(dados_funcionario)

dados_salvo.clear()
print(dados_salvo)

dados_funcionario.get

chaves = ['nome','idade','endereco']
valores = ['bruna',28,'rua das rosas']
dicionario = dict(zip(chaves,valores))
print(dicionario)

l1=list()
l2=list()
c=int(input('qtd: '))
while c>=len(l2):
    c>=1
    add1=str(input('chave: '))
    add2=str(input('valor: '))
    l1.append(add1)
    l2.append(add2)
    d=dict(zip(l1,l2))
print(d)